export const BOXES_INCOMING_COLUMNS = 'BOXES_INCOMING_COLUMNS'
export const BOXES_ASSIGNMENT_COLUMNS = 'BOXES_ASSIGNMENT_COLUMNS'
export const BOXES_CONTROL_COLUMNS = 'BOXES_CONTROL_COLUMNS'
export const BOXES_SIGN_COLUMNS = 'BOXES_SIGN_COLUMNS'
export const ROUTE_SIGN_SHOW = "SignShow"
