export { default as InnerLetterTemplate } from "./InnerLetterTemplate.vue"
export { default as ApplicationLetterTemplate } from "./ApplicationLetterTemplate.vue"
export { default as BusinessTripNoticeTemplate } from "./BusinessTripNoticeTemplate.vue"
export { default as ResolutionChairmanTemplate } from "./ResolutionChairman.vue"
export { default as ResolutionDeputyChairmanTemplate } from "./ResolutionDeputyChairman.vue"
export { default as ResolutionDefaultTemplate } from "./ResolutionDefault.vue"
