export const HR_BUSINESS_TRIP_COLUMNS = "HR_BUSINESS_TRIP_COLUMNS"
export const ROUTE_HR_BUSINESS_TRIP_LIST = "BusinessTripList"
export const ROUTE_HR_BUSINESS_TRIP_DETAIL = "BusinessTripDetail"
export const ROUTE_HR_BUSINESS_TRIP_PROCESS = "BusinessTripProcess"
export const ROUTE_HR_BUSINESS_TRIP_ADVANCE_REPORT_LIST = "BusinessTripAdvanceReportList"
export const ROUTE_HR_BUSINESS_TRIP_ADVANCE_REPORT_CREATE = "BusinessTripAdvanceReportCreate"
