export { default as ModalCancelSign } from './CancelSign.vue'
export { default as ModalComment } from './Comment.vue'
export { default as ModalDoneDocument } from './DoneDocument.vue'
export { default as ModalForwardDocument } from './ForwardDocument.vue'
export { default as ModalRate } from './Rate.vue'
export { default as ModalRemoveFromControl } from './RemoveFromControl.vue'
export { default as ModalShortDescription } from './ShortDescription.vue'
export { default as ModalWithFilters } from './WithFilters.vue'
